# Generated by Django 3.1.5 on 2021-02-17 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
